### ISSUE TITLE
Bug: website main.js not loading

### ISSUE THREAD

**Issue by keyboardfox** [BraveUX/for-the-badge#101]
Hello, I wanted to copy and add some of the great badges you have available but noticed that the website was not loading correctly. When pressing the copy markdown button nothing would happen, nor where the buttons responding (view all, search, about, etc).

I did double check my browser console and noticed the following:
`forthebadge.com/:6 GET https://forthebadge.com/main.js?v=1.3 net::ERR_ABORTED 404`

Browser tested with: Chrome, Firefox on Windows 10

Thanks

**Comment by XenottaBit** [comment]
Same issue here, none of the buttons respond to anything.

**Comment by XenottaBit** [comment]
I don't think that the main.js even exists here

**Comment by deepjyoti30** [comment]
+1, can confirm, happening for me as well. Nothing works and the error in the console is ```main.js is not found```, it was a 404.

**Comment by theJaxon** [comment]
Same issue, the website isn't functioning at all.

**Comment by ferradario** [comment]
Same here, website is down. No search, no copy, not usable.

Error in console:
`GET https://forthebadge.com/main.js?v=1.3 net::ERR_ABORTED 404`

**Comment by ekfuhrmann** [comment]
Thank you everyone for the reports, and apologies for the delay in resolving this issue. A month or so back we pushed out some package updates due to vulnerabilities (this project is quite old), which in turn broke the way our gulpfile bundled our scripts. While testing the package updates, everything was working for me since I still had some remnants of the old build in my dev directory. I've taken for granted the automated `cleaning`  I do on my more recent projects, so I wasn't even considering it.

Anyway I went ahead and resolved the issues as well as updated the entire build process as a whole so it's not 4 years old. This is something I was going to need to do anyway sooner rather than later so that we could begin handling some of the badge requests.

Again, sorry for the inconvenience and everything should be working again!
