### ISSUE TITLE
Made with SQLite badge pls

### ISSUE THREAD

**Issue by marchingon12** [BraveUX/for-the-badge#103]
One with 'made with sqlite' badge wouldbe great!

**Comment by ekfuhrmann** [comment]
Thanks for the suggestion, but please submit a PR with your desired badge. 

In order to have a better chance of it being approved and added quickly, it's very helpful to have you create the badge along with updating the README file in your PR. 

[You can view guidelines on contributing within the README file.](https://github.com/BraveUX/for-the-badge#contributing)
