### ISSUE TITLE
bug: USES BRAINS badge -- img rendering is full-page responsive lol

### ISSUE THREAD

**Issue by flsci** [BraveUX/for-the-badge#114]
This is just amazing -- I hope you'll keep this megababe version around forever. :heart:

Actually, adding supersize options for all the badges would be pretty rad. Consider this a shameless cookie bribe to make it happen.

#### INPUT:

```
[![forthebadge](https://forthebadge.com/images/badges/uses-brain.svg)](https://forthebadge.com)
```
---

##### [SCREENSHOT, 2020-09-18]

![ftb-big-brains-lol](https://user-images.githubusercontent.com/58527910/93639379-847b5880-f9be-11ea-9db0-56a274d0c875.png)

---

**Comment by ekfuhrmann** [comment]
Hah that's great, and a funny suggestion. In case you're curious, if the badge `svg` does not contain a defined `height` and `width` property, it will auto size causing the mega badge.

It unfortunately is difficult enough to get people to submit a single badge formatted properly, let alone both a fixed sized and scaled sized version, otherwise I'm all for it.

That said, if you want to strip out those properties and create your own mega badges to use, by all means go for it!
