### ISSUE TITLE
Add a badge for Julia

### ISSUE THREAD

**Issue by rahulkp220** [BraveUX/for-the-badge#68]
It would be great if there is a badge for [Julia](https://julialang.org/) as well.

**Comment by ekfuhrmann** [comment]
Thanks for the suggestion! If possible, please submit a PR with your desired badge. 

In order to have a better chance of it being approved and added quickly, it's very helpful to have you create the badge along with updating the README file in your PR. 

[You can view guidelines on contributing within the README file.](https://github.com/BraveUX/for-the-badge#contributing)

**Comment by scout119** [comment]
It is actually in #112

**Comment by ekfuhrmann** [comment]
PR has been accepted and merged into Master. Thanks @scout119
