### ISSUE TITLE
CC BY-NC-SA Badge

### ISSUE THREAD

**Issue by bhargavgv** [BraveUX/for-the-badge#76]

**Comment by ekfuhrmann** [comment]
Thanks for the suggestion! If possible would you not mind opening a PR for this change? 

In order to have a better chance of it being approved and added quickly, it's very helpful to have you create the badge along with updating the README file in your PR. 

[You can view guidelines on contributing within the README file.](https://github.com/BraveUX/for-the-badge#contributing)
