### ISSUE TITLE
[proposal] made with V

### ISSUE THREAD

**Issue by NotNite** [BraveUX/for-the-badge#97]
V is a stupid language, i don't actually program in it because it has several vulns but i think it would be a nice meme add

[v source code](https://github.com/vlang/v)

**Comment by ekfuhrmann** [comment]
Thanks for the suggestion, but please submit a PR with your desired badge should you want it added.

In order to have a better chance of it being approved and added quickly, it's very helpful to have you create the badge along with updating the README file in your PR. 

[You can view guidelines on contributing within the README file.](https://github.com/BraveUX/for-the-badge#contributing)
