### ISSUE TITLE
Powered by tiny hamsters badge

### ISSUE THREAD

**Issue by binyamin** [BraveUX/for-the-badge#98]
I could work on this, I just decided to open an issue first.

**Comment by ekfuhrmann** [comment]
Great badge suggestion, but please submit a PR for your desired badge. 

In order to have a better chance of it being approved and added quickly, it's very helpful to have you create the badge along with updating the README file in your PR. 

[You can view guidelines on contributing within the README file.](https://github.com/BraveUX/for-the-badge#contributing)
